
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/jszwedko/go-circleci"
  version = "0.2.0"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"
  version = "0.0.1"
